# Generated by Django 3.2.18 on 2023-05-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('preview', models.ImageField(upload_to='', verbose_name='изображение')),
                ('category', models.CharField(max_length=20, verbose_name='категория')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('made', models.DateField(verbose_name='изготовлено')),
                ('change', models.DateField(verbose_name='изменено')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
