# Generated by Django 3.2.18 on 2023-05-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
