# Generated by Django 4.2.2 on 2023-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_rename_name_category_name_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=255, unique_for_date='created', verbose_name='слаг')),
                ('the_text', models.CharField(max_length=200, verbose_name='текст')),
                ('image', models.ImageField(null=True, upload_to='blog/', verbose_name='изображение')),
                ('made', models.DateField(auto_now_add=True, verbose_name='изготовлено')),
                ('published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ('-made',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='change',
            field=models.DateField(auto_now=True, verbose_name='изменено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='made',
            field=models.DateField(auto_now_add=True, verbose_name='изготовлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(null=True, upload_to='product/', verbose_name='изображение'),
        ),
    ]
