# Generated by Django 4.2.2 on 2023-07-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_alter_version_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='изображение'),
        ),
    ]
